### ISSUE TITLE
This project is usable ?

### ISSUE THREAD

**Issue by faronov** [trycoon/liam-esp#2]
This not issue, this is a question 
I found your project, and it a very interesting project did you project worked?
do you have some instruction about how to connect everything?

**Comment by trycoon** [comment]
It’s still very much a work in progess, it can’t automatically mow your lawn just now, but you can manually drive it as a RC-car.
For something working I would suggest that you look at the Liam-project or Ardumower, they are however based around a Arduino and BWF-wires.
I’m aiming for a ESP32 and navigation by GNSS.

**Comment by faronov** [comment]
I already know about such great projects, but your project is also very interesting
when did you say GNSS what this mean?

**Comment by trycoon** [comment]
GNSS-RTK=https://en.wikipedia.org/wiki/Real-time_kinematic
A more precise GPS solution with a accuracy of a couple of centimeters (an inch), making it possible to control the mower using only a GNSS receiver instead of a perimeter wire.
