### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by faronov** [trycoon/liam-esp#4]
I tried to build your project
but it fails
`In file included from .piolibdeps/ESP Async WebServer/src/ESPAsyncWebServer.h:32:0,
from src/api.h:6,
from src/api.cpp:2:
src/WiFi.h:39:5: error: 'AsyncWebServer' does not name a type
AsyncWebServer& getWebServer();  // code-smell, we should think of a better way than to expose this inner reference when we need to register routes!
^
In file included from .piolibdeps/ESP Async WebServer/src/ESPAsyncWebServer.h:32:0,
from src/api.h:6,
from src/api.cpp:2:
src/WiFi.h:40:5: error: 'AsyncWebSocket' does not name a type
AsyncWebSocket& getWebSocketServer();  // code-smell, we should think of a better way than to expose this inner reference when we need to register routes!
^
src/WiFi.h:41:26: error: 'AsyncWebServerRequest' has not been declared
bool isAuthenticated(AsyncWebServerRequest *request);
^
src/WiFi.h:42:33: error: 'AsyncWebServerRequest' has not been declared
bool isAuthenticatedSession(AsyncWebServerRequest *request);`

**Comment by faronov** [comment]
this full log (truncated more error after last line)
> platformio run -t upload
> Processing nodemcuv2 (framework: arduino; platform: espressif32; board: nodemcu-32s)
> -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> LibraryManager: Installing id=346 @ 0.8.2
> Downloading  [####################################]  100%
> Unpacking  [####################################]  100%
> LibraryManager: Installing id=305 @ ^1.1.0
> Downloading  [####################################]  100%
> Unpacking  [####################################]  100%
> LibraryManager: Installing id=1826 @ ^1.0.0
> Downloading  [####################################]  100%
> Unpacking  [####################################]  100%
> LibraryManager: Installing AsyncTCP
> git version 2.17.1
> Cloning into '/Users/skype/liam-esp/.piolibdeps/_tmp_installing-R41EOl-package'...
> remote: Enumerating objects: 74, done.
> remote: Counting objects: 100% (74/74), done.
> remote: Compressing objects: 100% (46/46), done.
> remote: Total 142 (delta 33), reused 63 (delta 28), pack-reused 68
> Receiving objects: 100% (142/142), 50.10 KiB | 569.00 KiB/s, done.
> Resolving deltas: 100% (60/60), done.
> HEAD is now at d1f28ff Merge pull request #46 from atanisoft/patch-1
> LibraryManager: Installing ESP Async WebServer
> git version 2.17.1
> Cloning into '/Users/skype/liam-esp/.piolibdeps/_tmp_installing-FoCSqC-package'...
> remote: Enumerating objects: 1300, done.
> remote: Total 1300 (delta 0), reused 0 (delta 0), pack-reused 1300
> Receiving objects: 100% (1300/1300), 739.70 KiB | 880.00 KiB/s, done.
> Resolving deltas: 100% (876/876), done.
> HEAD is now at b0c6144 Update AsyncJson.h (#533)
> LibraryManager: Installing id=64 @ 5.13.4
> Downloading  [####################################]  100%
> Unpacking  [####################################]  100%
> LibraryManager: Installing id=1532 @ 1.0.3
> Downloading  [####################################]  100%
> Unpacking  [####################################]  100%
> LibraryManager: Installing id=5746 @ 1.4.2
> Downloading  [####################################]  100%
> Unpacking  [####################################]  100%
> LibraryManager: Installing id=1825 @ 1.1.0
> Downloading  [####################################]  100%
> Unpacking  [####################################]  100%
> PlatformManager: Installing espressif32
> Downloading  [####################################]  100%
> Unpacking  [####################################]  100%
> espressif32 @ 1.9.0 has been successfully installed!
> The platform 'espressif32' has been successfully installed!
> The rest of packages will be installed automatically depending on your build environment.
> PackageManager: Installing toolchain-xtensa32 @ ~2.50200.0
> Downloading  [####################################]  100%          
> Unpacking  [####################################]  100%          
> PackageManager: Installing tool-mkspiffs @ ~2.230.0
> Downloading  [####################################]  100%          
> Unpacking  [####################################]  100%
> PackageManager: Installing framework-arduinoespressif32 @ ~2.10002.190416
> Downloading  [####################################]  100%          
> Unpacking  [####################################]  100%          
> PackageManager: Installing tool-esptoolpy @ ~1.20600.0
> Downloading  [####################################]  100%
> Unpacking  [####################################]  100%
> Verbose mode can be enabled via `-v, --verbose` option
> CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/nodemcu-32s.html
> PLATFORM: Espressif 32 > NodeMCU-32S
> HARDWARE: ESP32 240MHz 320KB RAM (4MB Flash)
> DEBUG: CURRENT(jlink) EXTERNAL(esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
> Library Dependency Finder -> http://bit.ly/configure-pio-ldf
> LDF MODES: FINDER(chain) COMPATIBILITY(soft)
> Collected 35 compatible libraries
> Scanning dependencies...
> Dependency Graph
> |AsyncMqttClient> 0.8.2
> |   | AsyncTCP> 1.1.0 #d1f28ff
> | AsyncTCP> 1.1.0 #d1f28ff
> | ESP Async WebServer> 1.2.2 #b0c6144
> |   | AsyncTCP> 1.1.0 #d1f28ff
> |   | WiFi> 1.0
> |   | ArduinoJson> 5.13.4
> |   | FS> 1.0
> | ArduinoJson> 5.13.4
> | ArduinoLog> 1.0.3
> | SparkFun Ublox Arduino Library> 1.4.2
> |   | Wire> 1.0.1
> | SparkFun LSM9DS1 IMU> 1.1.0
> |   | Wire> 1.0.1
> |   | SPI> 1.0
> | Adafruit INA219> 1.0.4
> |   | Wire> 1.0.1
> | WiFi> 1.0
> | ESPmDNS> 1.0
> |   | WiFi> 1.0
> | Preferences> 1.0
> | FS> 1.0
> | Update> 1.0
> | Ticker> 1.1
> | DNSServer> 1.1.0
> |   | WiFi> 1.0
> | ArduinoOTA> 1.0
> |   | ESPmDNS> 1.0
> |   |   | WiFi> 1.0
> |   | Update> 1.0
> |   | WiFi> 1.0
> | Wire> 1.0.1
> | SPIFFS> 1.0
> |   | FS> 1.0
> Compiling .pioenvs/nodemcuv2/src/api.cpp.o
> Compiling .pioenvs/nodemcuv2/src/battery.cpp.o
> Compiling .pioenvs/nodemcuv2/src/configuration.cpp.o
> Compiling .pioenvs/nodemcuv2/src/cutter.cpp.o
> Compiling .pioenvs/nodemcuv2/src/definitions.cpp.o
> In file included from .piolibdeps/ESP Async WebServer/src/ESPAsyncWebServer.h:32:0,
> from src/api.h:6,
> from src/api.cpp:2:
> src/WiFi.h:39:5: error: 'AsyncWebServer' does not name a type
> AsyncWebServer& getWebServer();  // code-smell, we should think of a better way than to expose this inner reference when we need to register routes!
> ^

**Comment by trycoon** [comment]
It should build, I’ll try to clone out the project fresch when I get back from vacation. Maybe I have forgot to push something. Make sure you have the latest VSCode and Platform.io installed.

**Comment by faronov** [comment]
I update platformio and VSCto latest one
 platformio --version
PlatformIO, version 3.6.7
VSCode Version 1.34.0
still no luck

**Comment by trycoon** [comment]
I'm running:
VSCode: 1.36.1
PlatformIO, version 4.0.0
Espressif 32, version 1.9.0

Maybe you have not installed the "Espressif 32" library? Can you verify in PlatformIO?

**Comment by faronov** [comment]
As I know about Platformio it installs this library as a dependency
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/nodemcu-32s.html
PLATFORM: Espressif 32 1.9.0 > NodeMCU-32S

**Comment by faronov** [comment]
I also tried to remove ~/.platformio folder 
and when run upload  it downloaded automatically and installed

PlatformManager: Installing espressif32
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
espressif32 @ 1.9.0 has been successfully installed!
The platform 'espressif32' has been successfully installed!
The rest of packages will be installed automatically depending on your build environment.
PackageManager: Installing toolchain-xtensa32 @ ~2.50200.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
toolchain-xtensa32 @ 2.50200.80 has been successfully installed!
PackageManager: Installing tool-mkspiffs @ ~2.230.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
tool-mkspiffs @ 2.230.0 has been successfully installed!
PackageManager: Installing framework-arduinoespressif32 @ ~2.10002.190416
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
framework-arduinoespressif32 @ 2.10002.190628 has been successfully installed!
PackageManager: Installing tool-esptoolpy @ ~1.20600.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
tool-esptoolpy @ 1.20600.0 has been successfully installed!
CorePackageManager: Installing tool-scons @ ~2.20501.7
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
tool-scons @ 2.20501.7 has been successfully installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/nodemcu-32s.html
PLATFORM: Espressif 32 1.9.0 > NodeMCU-32S
......

but still same error

**Comment by faronov** [comment]
also maybe espressif library must be installed separately?

**Comment by trycoon** [comment]
Hmm, it has been a while since I set up my system from scratch, I'll try a
fresh install?
What OS do you run? So that I could try to mimic the installation. Maybe I
could improve the documentation in the process. ;-)

Have you done a "git pull" on my project to get the latest changes?

Den tis 16 juli 2019 kl 12:00 skrev faronov <notifications@github.com>:

**Comment by faronov** [comment]
I use macOS 10.13 and 10.14 
and of course, I use the latest git pull

**Comment by faronov** [comment]
also, keep in mind that platformio use home folder for storage libraries

**Comment by faronov** [comment]
do you have any news?
it still failed to build

**Comment by trycoon** [comment]
Yes, sorry that I have left you waiting!
I have fetched my work Macbook and tried install the project, and I can reproduce the error.
I have found what is wrong and will push a fix during next day.

**Comment by trycoon** [comment]
Done.
